### ISSUE TITLE
fix the hamburger menu for mobile screens

### ISSUE THREAD

**Issue by fykaa** [fykaa/Sample-Portfolio-for-Learners#22]
![image](https://user-images.githubusercontent.com/97490463/194709486-b3769a21-6831-4184-8d33-ed41c1a3f57d.png)

**Comment by Nevilkumar** [comment]
Hi @fykaa I would to work on this issue. Can you please assign it to me.

**Comment by 21omkarsase** [comment]
Hey @fykaa , I would like to work on it.
Can you assign this to me?

**Comment by fykaa** [comment]
@21omkarsase will assign if the first person to comment fails to send pr within the time.

**Comment by Nevilkumar** [comment]
@fykaa Can you please elaborate what needs to be done like do I need to fix the css or make the hamburger menu working?
