### ISSUE TITLE
improve UI of the entire learning page

### ISSUE THREAD

**Issue by fykaa** [fykaa/Sample-Portfolio-for-Learners#23]
![image](https://user-images.githubusercontent.com/97490463/194711159-b6b85fae-e589-4fb6-8d4c-99af6fea3ca1.png)

This issue won't be assigned, the best looking UI and effects PR will be merged. Try to add sections and improve the entire page, add smart CSS and menus

**Comment by Potato-29** [comment]
Hi @fykaa , I'd like to work on this issue, can you assign it for me? Thanks.

**Comment by Potato-29** [comment]
Hi @fykaa , do you have a design in mind?

**Comment by fykaa** [comment]
You can change the Background Image/color, interface, separate articles, proper padding and a row in the left for direct toggling . also updating the learning page to something like this ->
![image](https://user-images.githubusercontent.com/97490463/194901608-e6958792-24cd-4a14-837d-dd4831d53b87.png)
