### ISSUE TITLE
Link your projects to the home page

### ISSUE THREAD

**Issue by fykaa** [fykaa/Sample-Portfolio-for-Learners#34]
Add projects from [THIS FILE](https://github.com/fykaa/Sample-Portfolio-for-Learners/tree/master/projects) in the projects section of the Main Home Page of the website, such that a cover of the deployment is linked to it: - 

This Section - 
![image](https://user-images.githubusercontent.com/97490463/194754468-b244790e-a920-44a8-817e-94428cdaf0c3.png)

Like this - 
![image](https://user-images.githubusercontent.com/97490463/194754684-41fac719-e960-4d39-a36b-e33d584c6961.png)

**Comment by Potato-29** [comment]
assign this to me please

**Comment by fykaa** [comment]
@Potato-29 Please read [Instructions](https://github.com/fykaa/Sample-Portfolio-for-Learners/blob/master/README.md) before submitting PR

**Comment by Potato-29** [comment]
@fykaa understood till then can you check issue #32 its finished and I can make a PR

**Comment by Potato-29** [comment]
hi @fykaa does this look good? 
![image](https://user-images.githubusercontent.com/53327808/194766743-44d74006-a705-476b-ad22-9007e8e65798.png)

**Comment by fykaa** [comment]
It should take deployed site link for the button, and the cover image should be a that of the project's deployment first look

**Comment by fykaa** [comment]
updates @Potato-29

**Comment by Potato-29** [comment]
Ah sorry I was busy with work, you want the cover image to be the landing page of the deployed project right?

**Comment by Pragya2056** [comment]
However, if it still needs some work. Please assign me @fykaa
