### ISSUE TITLE
Improvements in forms page

### ISSUE THREAD

**Issue by sahadat-sk** [fykaa/Sample-Portfolio-for-Learners#55]
Hey @fykaa , I would like to Improve the forms page. Can I work on this? Also It would be great if this issue gets hacktoberfest tag.

**Comment by fykaa** [comment]
Please update Professional designs and follow all the steps below
Rules -


1) Must Follow all the steps from [Instructions](https://github.com/fykaa/Sample-Portfolio-for-Learners/#intructions-for-successfully-merged-pr-under-hacktoberfest-)
2) The PR should be valid and have no Merge Conflicts
3) DON'T spoil the Code indentations with any formatting tools such as prettier or VSC format
4) The PR Should be sent within 24 hours of Assignment, else will get reassigned to the next person.

**Comment by fykaa** [comment]
@sahadat-sk updates?

**Comment by sahadat-sk** [comment]
@fykaa I made the PR and it was also accepted. Should I close the issue now?

**Comment by komalioruganti** [comment]
Can I work on this?
