### ISSUE TITLE
Link Projects to homepage x2

### ISSUE THREAD

**Issue by fykaa** [fykaa/Sample-Portfolio-for-Learners#72]
Add projects from [THIS FILE](https://github.com/fykaa/Sample-Portfolio-for-Learners/tree/master/projects) in the projects section of the Main Home Page of the website, such that a cover of the deployment is linked to it: - 

This Section - 
![image](https://user-images.githubusercontent.com/97490463/194754468-b244790e-a920-44a8-817e-94428cdaf0c3.png)

Like this - 
![image](https://user-images.githubusercontent.com/97490463/194754684-41fac719-e960-4d39-a36b-e33d584c6961.png)

Rules -

1) Must Follow all the steps from [Instructions](https://github.com/fykaa/Sample-Portfolio-for-Learners/#intructions-for-successfully-merged-pr-under-hacktoberfest-)
2) The PR should be valid and have no Merge Conflicts
3) DON'T spoil the Code indentations with any formatting tools such as prettier or VSC format
4) The PR Should be sent within 24 hours of Assignment, else will get reassigned to the next person.

**Comment by Pragya2056** [comment]
@fykaa You can assign this to me

**Comment by fykaa** [comment]
done

**Comment by Pragya2056** [comment]
#73 
Please review it
